apiVersion: v1
kind: Service
metadata:
  name: deploy-svc
spec:
  selector:
    name: deploy
  type: ClusterIP
  ports:
  - name: deploy-svc-port
    protocol: TCP
    port: 80
    targetPort: "deploy-port"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      name: deploy
  template:
    metadata:
      labels:
        name: deploy
    spec:
      containers:
      - name: deploy
        image: rmerces/airportnames
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
        ports:
          - name: deploy-port 
            containerPort: 8080