apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator-hpa
  labels:
    app: load-generator-hpa
spec:
  selector:
    matchLabels:
      app: load-generator-hpa
  template:
    metadata:
      name: load-generator-hpa
      labels:
        app: load-generator-hpa
    spec:
      containers:
      - name: load-generator-hpa
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://10.245.243.216/airportName?iataCode=SDU; done"